name: production
description: Develop By Danny.
publish_to: 'none'

version: 1.6.2+3

environment:
  sdk: '>=3.1.0-12.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.0
  month_picker_dialog: ^6.0.3
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  horizontal_data_table: ^4.2.0
  fluttertoast: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  auto_size_text: ^3.0.0
  crypto: ^3.0.3
  graphview: ^1.2.0
  package_info_plus: ^8.3.0
  qr_flutter: ^4.1.0
  dotted_border: ^2.0.0+3
  dio: ^5.4.2
  syncfusion_flutter_datepicker: ^30.1.39
  multi_select_flutter: ^4.1.3
  flutter_slidable: ^4.0.0
  change_app_package_name: ^1.1.0
  local_auth: ^2.1.8
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  buttons_tabbar: ^1.3.12
  open_file: ^3.5.10
  url_launcher: ^6.3.1
  flutter_gantt: ^1.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "assets/images/logo_background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/shoes.png
    - assets/images/needle.png
    - assets/images/emma.png
    - assets/images/vulcanize.png
    - assets/images/cold_vulcanize.png
    - assets/images/cold_cement.png
    - assets/images/no_category.png
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf